# Generated by Django 5.2.6 on 2025-10-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_formassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="dashboard.form",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="dashboard.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="dashboard.formsubmission",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form", "user"], name="dashboard_f_form_id_fbfb7b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formsubmission",
            unique_together={("form", "user")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question"], name="dashboard_a_questio_30567c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("submission", "question")},
        ),
    ]
