# Generated by Django 5.2.6 on 2025-10-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_formsubmission_answer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="question",
            name="options_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="For multiple choice / dropdown, enter one option per line.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Open text"),
                    ("mcq", "Multiple choice"),
                    ("dropdown", "Dropdown"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(),
        ),
    ]
