# Generated by Django 5.2.6 on 2026-03-15 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('requires_default_form', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('account_created', 'Account Created'), ('default_form_pending', 'Default Form Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='sent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
