# Generated by Django 5.2.6 on 2026-03-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_license_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="options_text",
            field=models.TextField(
                blank=True, help_text="For multiple choice or licence label", null=True
            ),
        ),
    ]
