# Generated by Django 5.2.6 on 2026-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_onboardinginvite'),
        ('dashboard', '0008_alter_question_options_text'),
    ]

    operations = [
    ]
