# Generated by Django 5.2.6 on 2026-03-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_merge_20260327_0142"),
        ("dashboard", "0010_Project_invite_review_status"),
    ]

    operations = []
