# Generated by Django 5.2.6 on 2026-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_merge_20260327_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
