# Generated by Django 5.2.6 on 2026-04-20 07:30

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_licence_number_to_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_path),
        ),
        migrations.AlterField(
            model_name='credential',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='LicenceRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('reminder_band', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='dashboard.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_band', models.CharField(choices=[('6_month', '6 Months'), ('1_month', '1 Month'), ('2_week', '2 Weeks'), ('1_week', '1 Week'), ('3_day', '3 Days'), ('expired', 'Expired')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.credential')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('credential', 'reminder_band')},
            },
        ),
    ]
