# Generated by Django 5.2.6 on 2026-05-04 06:47

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_projectinvite_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=dashboard.models.upload_path
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="licence_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
