# Generated by Django 5.2.6 on 2026-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_credential_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencerenewalrequest',
            name='renewal_image',
            field=models.ImageField(blank=True, null=True, upload_to='renewal_uploads/'),
        ),
    ]
