# Generated by Django 5.2.6 on 2026-05-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_credential_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('phone', 'Phone Number'), ('radio', 'Multiple Choice (Single)'), ('checkbox', 'Multiple Choice (Multiple)'), ('dropdown', 'Dropdown'), ('file', 'File Upload'), ('licence_upload', 'Licence Image Upload')], default='text', max_length=20),
        ),
    ]
