# Generated by Django 5.2.6 on 2026-05-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_credential_image_and_more"),
        ("dashboard", "0014_licencerenewalrequest_renewal_image"),
    ]

    operations = []
