# Generated by Django 5.2.6 on 2026-05-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_credential_image_and_more"),
        ("dashboard", "0016_merge_20260514_1122"),
    ]

    operations = []
