# Generated by Django 5.2.6 on 2026-05-15 09:43

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_merge_20260515_0902"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Short Text"),
                    ("textarea", "Long Text"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("email", "Email"),
                    ("phone", "Phone Number"),
                    ("radio", "Multiple Choice (Single)"),
                    ("checkbox", "Multiple Choice (Multiple)"),
                    ("dropdown", "Dropdown"),
                    ("file", "File Upload"),
                    ("licence_upload", "Licence Image Upload"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("role", "Role"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document",
                    models.FileField(
                        upload_to=dashboard.models.approval_document_upload_path
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_documents",
                        to="dashboard.project",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_documents",
                        to="dashboard.projectrole",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_approval_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "title"],
            },
        ),
    ]
