# Generated by Django 5.2.6 on 2026-05-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_question_question_type_approvaldocument'),
        ('dashboard', '0018_formdraft'),
    ]

    operations = [
    ]
