# Generated by Django 5.2.6 on 2026-05-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_merge_20260504_2213'),
        ('dashboard', '0019_merge_20260517_0250'),
    ]

    operations = [
    ]
