# Generated by Django 5.2.6 on 2025-10-03 00:23

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_users(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    
    User.objects.create(
        username = 'admin@minemarshall.com',
        email = 'admin@minemarshall.com',
        first_name = "Admin",
        last_name = "Admin",
        password = make_password("password"),
        role = "admin",
        is_superuser = True,
        is_staff = True
    )
    User.objects.create(
        username = 'luke.kempson@gmail.com',
        email = 'luke.kempson@gmail.com',
        first_name = "Luke",
        last_name = "Kempson",
        password = make_password("password"),
        role = "manager",
        is_superuser = True,
        is_staff = True
    )
    User.objects.create(
        username = 'joshua.keen@connect.qut.edu.au',
        email = 'joshua.keen@connect.qut.edu.au',
        first_name = "Joshua",
        last_name = "Keen",
        password = make_password("password"),
        role = "user",
        is_superuser = False,
        is_staff = False
    )
    User.objects.create(
        username = 'melina.milios@connect.qut.edu.au',
        email = 'melina.milios@connect.qut.edu.au',
        first_name = "Melina",
        last_name = "Milios",
        password = make_password("password"),
        role = "user",
        is_superuser = False,
        is_staff = False
    )
    User.objects.create(
        username = 't8.osullivan@connect.qut.edu.au',
        email = 't8.osullivan@connect.qut.edu.au',
        first_name = "Timothy",
        last_name = "O'sullivan",
        password = make_password("password"),
        role = "user",
        is_superuser = False,
        is_staff = False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RunPython(create_users, reverse_code=migrations.RunPython.noop)
    ]
